name: Deliver new quiz answers from repo, daily.
on:
  schedule: # Run workflow automatically
    - cron: '30 14 * * *' # Runs @ 8PM
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  quiz-delivery:
    name: Deliver new quiz answers from repo, daily.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          FAUNADB_SERVER_SECRET: ${{ secrets.FAUNADB_SERVER_KEY }}
          DISCORD_KEY: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          answer: "true"
