name: Deliver new quiz answers from repo, daily.
on:
  schedule: # Run workflow automatically
    - cron: '30 14 * * *' # Runs @ 8PM
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  quiz-delivery:
    name: Deliver new quiz answers from repo, daily.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          answer: "true"
      - name: Increment File Number
        run: ./postscript.sh
